version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:

  BeforeInstall:
    - location: remove.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
